### ISSUE TITLE
Telegram group

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Elder-Support#1]

**Comment by zvili** [comment]
- Please define a Telegram group
- Send us your chosen users in Telegram
- Choose a group leader and share with us her/his user name.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement-B#2

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Accessibility-A#1

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Accessibility-B#1

**Comment by roy-shchory** [comment]
done
